### ISSUE TITLE
Le meilleur prix de livraison n'est correctement pris en compte dans le panier alors qu'il l'est dans l'étape de livraison

### ISSUE THREAD

**Issue by maximelebreton** [quadra-informatique/Prestashop-SoColissimo#10]
```Prestashop 1.6.1.0```
```Module 2.9.22```

**le transporteur 'commerces de proximité' est désactivé, mais c'est une spécificité du module so colissimo**
_______
![image](https://cloud.githubusercontent.com/assets/1072425/10432902/8adda360-710e-11e5-8661-fd8b814877fc.png)

**tarifs livraison à domicile HT**
_______
![image](https://cloud.githubusercontent.com/assets/1072425/10433374/9d970958-7111-11e5-9545-f2cc62234ffd.png)

**tarifs commerces de proximité HT**
_______
![image](https://cloud.githubusercontent.com/assets/1072425/10433380/aa06dde4-7111-11e5-96ed-9e2326566b38.png)

**Dans le panier, le meilleur prix de livraison affiché est 6.00€ TTC :**
_______
![image](https://cloud.githubusercontent.com/assets/1072425/10433447/2c3e823a-7112-11e5-9f87-0d779159c6be.png)

**Alors que de l'étape livraison, le meilleur prix affiché est de 5.00€ TTC**
_______
![image](https://cloud.githubusercontent.com/assets/1072425/10433412/ff3eec84-7111-11e5-8fda-703a5aaecc48.png)

**Comment by quadrateam** [comment]
Bonjour,

Il s'agit d'une volonté de la Poste afin de ne pas faire varier le tarif vers une augmentation suivant l'option que choisira le client. Le prix affiché est donc celui de base du transporteur, non le plus bas( qui correspond a une livraison spécifique en commerce).
Cependant si le client choisi à un moment une livraison commerçant dans l'api de la poste, son prix sera naturellement correctement répercuté au niveau du panier.

Cordialement,

**Comment by maximelebreton** [comment]
si c'est une volonté de la poste, le tarif devrait alors rester à celui de base entre le panier et l'étape de livraison (l'étape juste avant l'ouverture du module so colissimo), or ce n'est pas le cas.
Donc je pense qu'il s'agit bien d'un bug.

**Comment by quadrateam** [comment]
Le montant indiqué sur le page de choix des transporteurs fait clairement apparaitre la mention "a partir de". Il s'agit d'une indication tarifaire, non du tarif en lui même. 
L'idée est d'indiquer au client que selon son choix son tarif peut varier.

**Comment by maximelebreton** [comment]
Alors dans ce cas, donnez nous la possibilité d'afficher le transporteur "commerces de proximité".
car c'est votre module qui demande à ce que ce transporteur soit masqué, et cela créé une incohérence que vous ne pouvez pas ignorer, ni mettre sur le dos de la Poste.

**extrait de votre guide d'utilisateur**
____________
![image](https://cloud.githubusercontent.com/assets/1072425/10453510/eeef4608-71ac-11e5-9475-459987ff3796.png)

**Comment by quadrateam** [comment]
Bonjour,

Le module est en cohérence avec le mode fonctionnement de la solution Simplicité : 
- 1 seul mode de transport est proposé dans le panier
- Le choix entre la livraison à domicile ou en point commerçant se fait dans l'iframe Simplicité (et non dans PrestaShop).
L'utilité pour le module PrestaShop, d'avoir 2 transporteurs en Back Office est uniquement de pouvoir bénéficier de 2 grilles de saisies tarifaires indépendantes.

L'intégration de référence des fonctionnalités de Simplicité est disponible ici si besoin : http://www.demo-sosimplicite.colissimo.fr

Au vu de votre demande, il semble l'offre **SoColissimo Flexibilité** soit plus en cohérence avec votre besoin.

Cordialement,
