### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by cigartronic** [quadra-informatique/Prestashop-SoColissimo#4]
Lorsque le module est en mode fancybox , il y a un appel qui est fait hors SSL alors que la page
est en SSL. Du coup la reqûete est bloquée et la fancy box ne s'affiche pas.

l'appel est fait : http://www.example.fr/modules/socolissmo/redirect.php?first_cal .......
Le baseDir dans la console indique pourtant bien l'url en https.

La dernière version est installée

C'est comme si il y avait un override quelque part.

**Comment by sappasamy** [comment]
Bonjour,

Quelle version de Prestashop utilisez-vous?

Cordialement,

**Comment by cigartronic** [comment]
bonjour,

La varsion 1.6.0.10

Cordialement

Christopher KENNY
tél : 06 14 51 39 26
Email : christopher@cigartronic.fr <mailto:christopher@cigartronic.fr>
Site : www.cigartronic.fr




Distributeur Officiel 


http://www.aspirecig.com/business-partners/

**Comment by sappasamy** [comment]
Je ne trouve pas de version 1.6.0.10 sur Prestashop.

https://www.prestashop.com/fr/versions-developpeurs#previous-version

Pouvez-vous vérifier de nouveau votre version de Prestashop?

Cordialement,

**Comment by cigartronic** [comment]
Bonjour,

voici la capture d’écran.

Cordialement




Christopher KENNY
tél : 06 14 51 39 26
Email : christopher@cigartronic.fr <mailto:christopher@cigartronic.fr>
Site : www.cigartronic.fr




Distributeur Officiel 


http://www.aspirecig.com/business-partners/

**Comment by sappasamy** [comment]
Je ne trouve pas de pièce joint à votre message.

Cordialement,

**Comment by cigartronic** [comment]
Il s’agissait d’une copie d’écran montrant bien la version 1.6.0.10 de prestashop
qui s’affiche en bas d’écran dans l’admin.

Cordialement

**Comment by quadrateam** [comment]
Bonjour,

La version 2.9.20 corrige le probleme de SSL, cette version est en cours de validation chez prestashop.
Une fois validée, vous pourrez mettre a jour votre module et vous n'aurez qu'a passer votre url so et so mobile en https pour que cela fonctionne.

Pour info ces urls devront ressemblées à 
https://ws.colissimo.fr/pudo-fo-frame/storeCall.do
et
https://ws-mobile.colissimo.fr/
Bien cordialement,
