### ISSUE TITLE
Iframe URL in order process not found

### ISSUE THREAD

**Issue by leto3087** [quadra-informatique/Prestashop-SoColissimo#6]
Prestashop 1.6.0.11
Module version : 2.9.21
 
Hi, i've a problem after the choice of so colissimo in order process.
First, the error was : "Error code: Wrong sign or number version"

I added "http" prefix of the FO address. The error is gone but now I have a new problem. The URL called by the iframe is not found. Yet my name and my FO encryption key is correct. 

Have you an idea?

**Comment by quadrateam** [comment]
Hi leto,

You should not add http to your prefix, it is added automatically. Module will add http or https to that url if you have SSL.

Your error code 'Error code: Wrong sign or number version' means that the signature is incorrect when checked by LaPOSTE's API . Please check informations on module side(id, key, overcost, etc...)  are the same in your COLISPOSTE account.

If you are a new subscriber to La poste. Your account can take time to be truly actived on laposte side.  This error code: "Wrong sign..." is typical to new subscriber. In that cas you don't have to do anything, when your account will be actived on La poste side, module wont' get that error code anymore.

Best regards

**Comment by leto3087** [comment]
ok, thanks !
It is already 15 days since my account was created in SO COLISSIMO...
I will wait.
