### ISSUE TITLE
Socolissimo Undefined index: cecountry

### ISSUE THREAD

**Issue by bumarius** [quadra-informatique/Prestashop-SoColissimo#7]
Hello,

In back office when we go to detail order we have this message:
    PrestaShop Version:
    1.6.1.1
    Module version:
    2.9.21
![sans titre-1](https://cloud.githubusercontent.com/assets/11003699/10185637/883a8934-674a-11e5-9f3d-439dc282a2c8.jpg)

Notice à la ligne 862 du fichier /var/www/modules/socolissimo/socolissimo.php
[8] Undefined index: cecountry

Notice à la ligne 863 du fichier /var/www/modules/socolissimo/socolissimo.php
[8] Undefined index: name

This message is displayed not every time but when the prestashop cache is enables we see this message every time.

We use xcache for optimisation.

Best regards
Marius

**Comment by quadrateam** [comment]
Hello,

I see you have already contact us by our site web, i close this issue on github. We're still waiting for your response.

Regards,

**Comment by benjbmc** [comment]
Hello @quadrateam,

I have the exact same error than Marius, could you say how to fix this ? 
Thanks in advance.

FYi :
- Module version : 3.50.5
- Prestashop version : 1.6.1.11

**Comment by julien-brouwers** [comment]
Hello @benjbmc 

Have you got a custom theme ?
