### ISSUE TITLE
la détection et redirection vers ws-mobile.colissimo.fr ne se fait pas

### ISSUE THREAD

**Issue by maximelebreton** [quadra-informatique/Prestashop-SoColissimo#8]
Sur mobile, lors de la redirection vers le mode de livraison, l'url appelée devrait être ```ws-mobile.colissimo.fr```
mais c'est l'url classique ```ws.colissimo.fr``` qui est appelée.

Prestashop 1.6.0
Module Socolissimo 2.9.22

Testé sur un HTC One  - Android 5.0.2
(mais aussi via les chrome developper tools en profil iPhone ou Android)

![image](https://cloud.githubusercontent.com/assets/1072425/10368671/be7a556e-6dd6-11e5-9360-f4ee38b1bec6.png)

![image](https://cloud.githubusercontent.com/assets/1072425/10368656/aa317df8-6dd6-11e5-851f-ebf682bd7821.jpg)

![image](https://cloud.githubusercontent.com/assets/1072425/10368754/2f23fee6-6dd7-11e5-809c-d93f1667a794.png)

**Comment by quadrateam** [comment]
Bonjour,

La detection de l'agent utilisateur (pc, portable, etc...) se fait dans le module en utilisant la mehode de prestashop Context::getContext()->getMobileDevice().

Avez vous pu tester sur d'autres appareils mobiles ? Si oui avez vous le meme resultat ?

Cordialement,

**Comment by maximelebreton** [comment]
ok, le problème venait effectivement d'un réglage de Prestashop qui se situe au niveau du thème.
Car bien que celui ci soit responsive, il faut le spécifier dans les réglages.

Dans préférences > thèmes, puis dans l'onglet mobile > Activer le thème mobile.
![image](https://cloud.githubusercontent.com/assets/1072425/10395064/4534aa5e-6e9b-11e5-903b-04dd69d45327.png)

Tout rentre dans l'ordre ensuite.
