### ISSUE TITLE
Le module ne tiens pas compte des tarifs transporteur "mon commercant" pour la Belgique

### ISSUE THREAD

**Issue by maximelebreton** [quadra-informatique/Prestashop-SoColissimo#9]
Pour la France métropolitaine, aucun souci, les tarifs "livraison à domicile" et "mon commerçant" sont bien pris en compte.
Mais pour la Belgique, si on choisi "mon commerçant", c'est le tarif "livraison à domicile" qui est sélectionné...

Dans l'exemple ci dessous, je choisis une adresse en Belgique et la livraison "mon commerçant".
Le tarif devrait être donc de 2,00 € (+ surcout & TVA) comme configuré dans le transporteur.
Mais au lieu de ça, il est à 13,68 €... (soit le tarif de livraison à domicile)

```Prestashop 1.6.1.0```
```Module Socolissimo 2.9.22```

**Réglages module :**
______
![image](https://cloud.githubusercontent.com/assets/1072425/10369136/02f1501a-6dd9-11e5-8f3e-72201af45b5a.png)
![image](https://cloud.githubusercontent.com/assets/1072425/10369949/2ac9136c-6ddd-11e5-85d1-7f8819f806b9.png)

**Transporteurs :**
______
![image](https://cloud.githubusercontent.com/assets/1072425/10369601/70c1250a-6ddb-11e5-92ae-f3968a7475bd.png)

**Tarifs transporteur So Colissimo (livraison à domicile)**
______
![image](https://cloud.githubusercontent.com/assets/1072425/10369656/ac332d22-6ddb-11e5-8455-0807adb104bc.png)

**Tarifs transporteur So Colissimo - Commerces de proximité (mon commerçant)**
______
![image](https://cloud.githubusercontent.com/assets/1072425/10369669/b5b38536-6ddb-11e5-97be-d3624a980056.png)

**Tarif final incorrect...**
______
![image](https://cloud.githubusercontent.com/assets/1072425/10369691/d5d80364-6ddb-11e5-9ec7-f090c2c107a3.png)

**Comment by quadrateam** [comment]
Bonjour,

La differenciation de tarif pour les livraisons en commerce de proximité n'est effective qu'en France, celle ci n'est pas active pour la Belgique. Il s'agit d'une volonté de la Poste.

Il s'agit donc du fonctionnement voulu pour le module.

Bien cordialement,

**Comment by maximelebreton** [comment]
Il serait peut être intéressant de l'indiquer dans le module alors,
car on perds un temps fou à essayer de comprendre ce qui se passe,
et ces bidouilles qui vont en contre sens du fonctionnement de Prestashop font que l'expérience utilisateur de votre module est assez mauvaise.
